image:
  repository: pmwrp/rp-live
  tag: "0.0.24"

source:
  namespace: redpanda
  # the redpanda pod prefix is the pod name but without the hyphen and ordinal (so for example redpdpan
  redpanda_pod_prefix: redpanda
  kafka_port: 9093
  admin_port: 9644
#  sasl:
#    enabled: true
#    secret: source
#  tls:
#    enabled: true
#    skip_cert_verify: true

destination:
  seed_broker: "https://redpanda-0.o11y.cs.redpanda.com:443"
  logs_topic: logs
  metrics_topic: metrics
  secret: destination

logs:
  enabled: true

metrics:
  enabled: true