apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-log-reader
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-log-reader
rules:
  - apiGroups: [ "" ]
    resources: [ "pods", "pods/log", "services"]
    verbs: [ "get", "list", "watch"]
  - apiGroups: [ "extensions" ]
    resources: [ "deployments" ]
    verbs: [ "get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-log-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-log-reader
subjects:
  - kind: ServiceAccount
    name: pod-log-reader
